# Generated by Django 6.1.1 on 2026-09-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('SUSPENDED', 'Suspended'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
