# Generated by Django 5.2.17 on 2026-09-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_businesssetting_customernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
