# Generated by Django 6.1.1 on 2026-09-15 06:16

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booking_type', models.CharField(choices=[('REGULAR', 'Regular Booking'), ('RECURRING', 'Recurring Booking'), ('GROUP', 'Group / Team Booking'), ('WALK_IN', 'Walk-in Booking')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('PAYMENT_PENDING', 'Payment Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked-in'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show'), ('REFUNDED', 'Refunded')], db_index=True, default='CONFIRMED', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('pricing_breakdown', models.JSONField(blank=True, default=dict)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_checkins', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('slots', models.ManyToManyField(blank=True, related_name='slot_bookings', to='turfs.timeslot')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='turfs.turf')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
