# Generated by Django 5.2.17 on 2026-09-24 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('turfs', '0004_rename_turfs_times_turf_id_bbeb68_idx_slot_turf_date_stat_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'date', 'status'], name='booking_cust_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'start_time'], name='booking_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['turf', 'date'], name='booking_turf_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'date'], name='booking_stat_date_idx'),
        ),
    ]
