# Generated by Django 6.1.1 on 2026-09-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_cust_date_idx_and_more'),
        ('turfs', '0005_turf_deleted_at_turf_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='turfs.turf'),
        ),
    ]
