# Generated by Django 6.1.1 on 2026-09-15 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('VALID', 'Booking Verified — Entry Allowed'), ('INVALID', 'Invalid Booking'), ('ALREADY_USED', 'Customer Already Checked In'), ('EXPIRED', 'Booking Expired')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_records', to='bookings.booking')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('jwt_token', models.TextField()),
                ('qr_base64', models.TextField(blank=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_ticket', to='bookings.booking')),
            ],
        ),
    ]
