# Generated by Django 5.2.17 on 2026-09-15 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('qr_system', '0001_initial'),
        ('turfs', '0002_turf_dimensions_turf_dugout_spec_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrticket',
            name='booking',
        ),
        migrations.CreateModel(
            name='QRCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('credential_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('credential_version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_until', models.DateTimeField(db_index=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('checkin_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('qr_base64', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_credential', to='bookings.booking')),
                ('checkin_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Credential',
                'verbose_name_plural': 'QR Credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('QR_SCAN', 'QR Camera Optical Scan'), ('MANUAL_CODE', 'Manual Booking Code Lookup'), ('ADMIN_OVERRIDE', 'Manager / Admin Override'), ('WALK_IN', 'Walk-in Desk Reception')], default='QR_SCAN', max_length=30)),
                ('decision', models.CharField(choices=[('ALLOW', 'Entry Approved'), ('DENY', 'Entry Denied'), ('WARNING', 'Warning / Partial Payment Required'), ('MANUAL_REVIEW', 'Manual Review Required')], default='ALLOW', max_length=30)),
                ('reason_code', models.CharField(default='ENTRY_APPROVED', max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('override_reason', models.TextField(blank=True)),
                ('device_identifier', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='bookings.booking')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_operations', to=settings.AUTH_USER_MODEL)),
                ('turf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turf_check_ins', to='turfs.turf')),
                ('qr_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='qr_system.qrcredential')),
            ],
            options={
                'verbose_name': 'Gate Check-In',
                'verbose_name_plural': 'Gate Check-Ins',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.DeleteModel(
            name='CheckInRecord',
        ),
        migrations.DeleteModel(
            name='QRTicket',
        ),
    ]
