# Generated by Django 5.2.17 on 2026-09-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_system', '0002_remove_qrticket_booking_qrcredential_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='method',
            field=models.CharField(choices=[('QR_SCAN', 'QR Camera Optical Scan'), ('MANUAL_CODE', 'Manual Booking Code Lookup'), ('ADMIN_OVERRIDE', 'Admin Override'), ('WALK_IN', 'Walk-in Desk Reception')], default='QR_SCAN', max_length=30),
        ),
    ]
