# Generated by Django 6.1.1 on 2026-09-15 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmed'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_PENDING', 'Payment Pending'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_RESCHEDULED', 'Booking Rescheduled'), ('REFUND_PROCESSED', 'Refund Processed'), ('UPCOMING_REMINDER', 'Upcoming Match Reminder'), ('REVIEW_REQUEST', 'Review Request'), ('COUPON_ALERT', 'Offer / Coupon Alert'), ('MEMBERSHIP_ALERT', 'Membership Update'), ('SYSTEM_ALERT', 'System Alert')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
