# Generated by Django 6.1.1 on 2026-09-15 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earned (+)'), ('REDEEM', 'Redeemed (-)'), ('BONUS', 'Bonus Points (+)'), ('EXPIRE', 'Expired (-)')], max_length=10)),
                ('source', models.CharField(choices=[('BOOKING', 'Completed Turf Booking'), ('PROMOTION', 'Seasonal Promotion'), ('REFERRAL', 'Referral Completed'), ('ADMIN', 'Manual Admin Reward')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit (+)'), ('DEBIT', 'Debit (-)')], max_length=10)),
                ('source', models.CharField(choices=[('REFUND', 'Booking Refund'), ('PROMOTIONAL', 'Promotional Bonus'), ('REFERRAL', 'Referral Reward'), ('ADMIN', 'Admin Adjustment'), ('REDEMPTION', 'Booking Payment'), ('TOP_UP', 'Direct Wallet Top-up')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
