# Generated by Django 6.1.1 on 2026-09-15 07:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tier_level', models.IntegerField(default=1, help_text='1=Silver, 2=Gold, 3=Platinum')),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('priority_booking_days', models.IntegerField(default=7, help_text='Can book up to N days in advance')),
                ('loyalty_point_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=499.0, max_digits=8)),
                ('annual_price', models.DecimalField(decimal_places=2, default=4999.0, max_digits=8)),
                ('features', models.JSONField(default=list)),
                ('badge_color', models.CharField(default='#10B981', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscribers', to='memberships.membershipplan')),
            ],
        ),
    ]
