# Generated by Django 6.1.1 on 2026-09-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.2, max_digits=4)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('WEEKDAY', 'Weekday Standard'), ('WEEKEND', 'Weekend Premium'), ('PEAK_HOUR', 'Peak Hour Surcharge'), ('OFF_PEAK', 'Off-Peak Discount'), ('HOLIDAY', 'Holiday Pricing'), ('SPECIAL_EVENT', 'Special Event Pricing'), ('PROMOTIONAL', 'Promotional Discount'), ('LAST_MINUTE', 'Last-Minute Discount'), ('EARLY_BOOKING', 'Early-Bird Discount')], max_length=30)),
                ('adjustment_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (+/- %)'), ('FIXED', 'Fixed Amount (+/- ₹)')], default='PERCENTAGE', max_length=20)),
                ('adjustment_value', models.DecimalField(decimal_places=2, help_text='e.g. 20.00 for +20% or -10.00 for 10% discount', max_digits=8)),
                ('applicable_days', models.JSONField(blank=True, default=list, help_text='List of day integers 0=Mon, 6=Sun')),
                ('start_time', models.TimeField(blank=True, help_text='Start time for peak/off-peak', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time for peak/off-peak', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='turfs.turf')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('turf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.turf')),
            ],
        ),
    ]
