# Generated by Django 5.2.17 on 2026-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('turfs', '0004_rename_turfs_times_turf_id_bbeb68_idx_slot_turf_date_stat_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialevent',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['is_active', 'priority'], name='pricing_act_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='specialevent',
            index=models.Index(fields=['date'], name='spevent_date_idx'),
        ),
    ]
