# Generated by Django 6.1.1 on 2026-09-15 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='activity', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('sport_type', models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Box Cricket'), ('MULTI_SPORT', 'Multi-Sport'), ('BADMINTON', 'Badminton'), ('TENNIS', 'Tennis')], default='FOOTBALL', max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per 1-hour slot', max_digits=10)),
                ('capacity', models.IntegerField(default=14, help_text='Recommended max players')),
                ('images', models.JSONField(default=list, help_text='List of image URLs')),
                ('operating_hours_start', models.TimeField(default='06:00:00')),
                ('operating_hours_end', models.TimeField(default='23:00:00')),
                ('slot_duration_minutes', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='turfs', to='turfs.facility')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Temporarily Locked'), ('BOOKED', 'Booked'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=50)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_slots', to=settings.AUTH_USER_MODEL)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='turfs.turf')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['turf', 'date', 'status'], name='turfs_times_turf_id_bbeb68_idx')],
            },
        ),
    ]
