# Generated by Django 6.1.1 on 2026-09-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='dimensions',
            field=models.CharField(default='110ft x 70ft (7v7 Standard)', help_text='Pitch playing dimensions', max_length=100),
        ),
        migrations.AddField(
            model_name='turf',
            name='dugout_spec',
            field=models.CharField(default='14-Player Shaded Dugout & Tactical Board', help_text='Dugout capacity and amenities', max_length=150),
        ),
        migrations.AddField(
            model_name='turf',
            name='fast_fill_threshold',
            field=models.IntegerField(default=4, help_text='Remaining slots threshold for fast-fill badge'),
        ),
        migrations.AddField(
            model_name='turf',
            name='is_fifa_certified',
            field=models.BooleanField(default=True, help_text='FIFA certification status'),
        ),
        migrations.AddField(
            model_name='turf',
            name='lighting_spec',
            field=models.CharField(default='400 Lux Anti-Glare LED Floodlights', help_text='Lighting specification', max_length=150),
        ),
        migrations.AddField(
            model_name='turf',
            name='surface_spec',
            field=models.CharField(default='50mm FIFA Quality Pro Artificial Turf', help_text='Turf surface specification', max_length=150),
        ),
    ]
