# Generated by Django 6.1.1 on 2026-09-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_turf_dimensions_turf_dugout_spec_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('turf', 'date', 'start_time')},
        ),
    ]
