# Generated by Django 5.2.17 on 2026-09-24 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_alter_timeslot_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timeslot',
            new_name='slot_turf_date_stat_idx',
            old_name='turfs_times_turf_id_bbeb68_idx',
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['status', 'locked_until'], name='slot_lock_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['turf', 'date', 'start_time'], name='slot_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='turf',
            index=models.Index(fields=['is_active', 'sport_type'], name='turf_active_sport_idx'),
        ),
    ]
