# Generated by Django 6.1.1 on 2026-09-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_rename_turfs_times_turf_id_bbeb68_idx_slot_turf_date_stat_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='turf',
            index=models.Index(fields=['is_deleted', 'is_active'], name='turf_del_act_idx'),
        ),
    ]
