# Generated by Django 6.1.1 on 2026-10-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0005_turf_deleted_at_turf_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Temporarily Locked'), ('BOOKED', 'Booked'), ('MAINTENANCE', 'Under Maintenance'), ('BLOCKED', 'Admin Blocked')], default='AVAILABLE', max_length=20),
        ),
    ]
