# Generated by Django 5.2.17 on 2026-09-30 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_turf'),
        ('payments', '0005_payment_payment_created_stat_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status', 'created_at'], name='payment_method_stat_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payment_stat_paid_idx'),
        ),
    ]
